from sqlalchemy import select

from app.db.session import SessionLocal, create_all
from app.models import Organization, OrganizationProfile, Source


def seed_default_sources(db, organization: Organization) -> dict[str, int]:
    source_definitions = [
        {
            "key": "simpler-grants",
            "name": "Simpler Grants Search",
            "base_url": "https://simpler.grants.gov/search",
            "country": "United States",
            "region": "North America",
            "source_type": "html",
            "category": ["grants", "federal funding"],
            "allowed_domains": ["simpler.grants.gov"],
        },
        {
            "key": "grants-gov-forecast",
            "name": "Grants.gov Forecast Feed",
            "base_url": "https://www.grants.gov/rss/GG_ForecastOpportunities.xml",
            "country": "United States",
            "region": "North America",
            "source_type": "rss",
            "category": ["grants", "federal funding"],
            "allowed_domains": ["www.grants.gov"],
        },
        {
            "key": "grants-gov",
            "name": "Grants.gov Search API",
            "base_url": "https://api.grants.gov/v1/api/search2",
            "country": "United States",
            "region": "North America",
            "source_type": "api",
            "category": ["grants", "federal funding"],
            "allowed_domains": ["api.grants.gov"],
        },
        {
            "key": "grants-gov-rss",
            "name": "Grants.gov RSS Opportunities",
            "base_url": "https://www.grants.gov/rss/GG_OppModByCategory.xml",
            "country": "United States",
            "region": "North America",
            "source_type": "rss",
            "category": ["grants", "federal funding", "rss"],
            "allowed_domains": ["www.grants.gov"],
        },
        {
            "key": "nsf-funding-rss",
            "name": "NSF Funding Opportunities RSS",
            "base_url": "https://www.nsf.gov/rss/rss_www_funding_pgm_annc_inf.xml",
            "country": "United States",
            "region": "North America",
            "source_type": "rss",
            "category": ["grants", "research", "innovation"],
            "allowed_domains": ["nsf.gov"],
        },
        {
            "key": "nsf-funding",
            "name": "NSF Funding Search",
            "base_url": "https://www.nsf.gov/funding",
            "country": "United States",
            "region": "North America",
            "source_type": "html",
            "category": ["grants", "research", "innovation"],
            "allowed_domains": ["nsf.gov"],
        },
        {
            "key": "minciencias",
            "name": "Minciencias Convocatorias",
            "base_url": "https://minciencias.gov.co/convocatorias/todas",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "ciencia", "innovacion"],
            "allowed_domains": ["minciencias.gov.co"],
        },
        {
            "key": "icetex-vigentes",
            "name": "ICETEX Becas Vigentes",
            "base_url": "https://web.icetex.gov.co/becas/becas-para-estudios-en-el-exterior/becas-vigentes",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["becas", "cooperacion", "educacion"],
            "allowed_domains": ["web.icetex.gov.co"],
        },
        {
            "key": "icetex-otras-becas",
            "name": "ICETEX Otras Becas",
            "base_url": "https://web.icetex.gov.co/becas/becas-para-estudios-en-el-exterior",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["becas", "cooperacion", "educacion"],
            "allowed_domains": ["web.icetex.gov.co"],
        },
        {
            "key": "mineducacion-becas",
            "name": "MEN Becas y Convocatorias",
            "base_url": "https://www.mineducacion.gov.co/portal/micrositios-institucionales/Cooperacion-Internacional/Becas-convocatorias-y-premios-de-cooperacion-internacional/420940:Becas-y-convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["becas", "cooperacion", "educacion"],
            "allowed_domains": ["mineducacion.gov.co", "www.mineducacion.gov.co"],
        },
        {
            "key": "innpulsa",
            "name": "iNNpulsa Convocatorias",
            "base_url": "https://convocatorias.innpulsacolombia.com/api/convocatorias?active_only=true&include_private=false&include_archive=false",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "api",
            "category": ["convocatorias", "emprendimiento", "innovacion"],
            "allowed_domains": ["innpulsacolombia.com", "convocatorias.innpulsacolombia.com"],
        },
        {
            "key": "apc-colombia",
            "name": "APC Colombia Convocatorias",
            "base_url": "https://www.apccolombia.gov.co/seccion/modalidades-de-cooperacion",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "cooperacion", "internacional"],
            "allowed_domains": ["apccolombia.gov.co"],
        },
        {
            "key": "eu-funding-tenders",
            "name": "EU Funding & Tenders",
            "base_url": "https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/calls-for-proposals",
            "country": "European Union",
            "region": "Europe",
            "source_type": "hybrid",
            "category": ["grants", "research", "innovation"],
            "allowed_domains": ["ec.europa.eu"],
        },
        {
            "key": "innovamos-global-innovation-fund",
            "name": "Innovamos - Global Innovation Fund",
            "base_url": "https://www.innovamos.gov.co/instrumentos/convocatoria-subvenciones-a-proyectos-en-alianza-con",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["innovacion", "cooperacion", "financiacion"],
            "allowed_domains": ["innovamos.gov.co", "www.innovamos.gov.co"],
        },
        {
            "key": "innovamos-fid",
            "name": "Innovamos - Fondo para la Innovación en el Desarrollo",
            "base_url": "https://www.innovamos.gov.co/instrumentos/internacional-proyectos-fondo-para-la-innovacion-en",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["innovacion", "cooperacion", "financiacion"],
            "allowed_domains": ["innovamos.gov.co", "www.innovamos.gov.co"],
        },
        {
            "key": "ukri-opportunities",
            "name": "UKRI Funding Finder",
            "base_url": "https://www.ukri.org/opportunity/",
            "country": "United Kingdom",
            "region": "Europe",
            "source_type": "html",
            "category": ["grants", "research", "innovation"],
            "allowed_domains": ["ukri.org", "www.ukri.org"],
        },
        {
            "key": "unesco-call-for-proposals",
            "name": "UNESCO Call for Proposals",
            "base_url": "https://www.unesco.org/en/articles/call-proposals",
            "country": "International",
            "region": "Global",
            "source_type": "html",
            "category": ["cooperation", "research", "innovation"],
            "allowed_domains": ["unesco.org", "www.unesco.org"],
        },
        {
            "key": "undef",
            "name": "UN Democracy Fund",
            "base_url": "https://www.un.org/democracyfund/en/apply-for-funding",
            "country": "International",
            "region": "Global",
            "source_type": "html",
            "category": ["cooperation", "governance", "funding"],
            "allowed_domains": ["un.org", "www.un.org"],
        },
        {
            "key": "unwomen-innovate",
            "name": "UN Women Innovation Calls",
            "base_url": "https://www.unwomen.org/en/how-we-work/innovation-and-technology",
            "country": "International",
            "region": "Global",
            "source_type": "html",
            "category": ["innovation", "cooperation", "global"],
            "allowed_domains": ["unwomen.org"],
        },
        {
            "key": "novo-nordisk-grants",
            "name": "Novo Nordisk Foundation Grants",
            "base_url": "https://novonordiskfonden.dk/wp-json/wp/v2/grant?per_page=100&status=publish",
            "country": "Denmark",
            "region": "Europe",
            "source_type": "api",
            "category": ["grants", "health", "biotech", "research"],
            "allowed_domains": ["novonordiskfonden.dk"],
            "scraping_frequency": "daily",
        },
        {
            "key": "wellcome-grants",
            "name": "Wellcome Trust Funding",
            "base_url": "https://wellcome.org/research-funding/schemes",
            "country": "United Kingdom",
            "region": "Europe",
            "source_type": "html",
            "category": ["grants", "health", "research"],
            "allowed_domains": ["wellcome.org", "www.wellcome.org"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "horizon-europe-sedia",
            "name": "Horizon Europe SEDIA API",
            "base_url": "https://api.tech.ec.europa.eu/search-api/prod/rest/search",
            "country": "European Union",
            "region": "Europe",
            "source_type": "api",
            "category": ["grants", "research", "innovation", "horizon europe"],
            "allowed_domains": ["api.tech.ec.europa.eu", "ec.europa.eu"],
            "scraping_frequency": "daily",
        },
        {
            "key": "gates-foundation-grants",
            "name": "Gates Foundation Open Opportunities",
            "base_url": "https://www.gatesfoundation.org/about/how-we-work/grants",
            "country": "International",
            "region": "Global",
            "source_type": "html",
            "category": ["grants", "health", "development"],
            "allowed_domains": ["gatesfoundation.org", "www.gatesfoundation.org"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "dfg-grants",
            "name": "DFG Funding Opportunities",
            "base_url": "https://www.dfg.de/en/research_funding/",
            "country": "Germany",
            "region": "Europe",
            "source_type": "html",
            "category": ["grants", "research", "funding"],
            "allowed_domains": ["dfg.de", "www.dfg.de"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "colfuturo-convocatorias",
            "name": "Colfuturo Convocatorias",
            "base_url": "https://www.colfuturo.org/convocatorias/",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["becas", "cooperacion", "educacion"],
            "allowed_domains": ["colfuturo.org", "www.colfuturo.org"],
            "scraping_frequency": "daily",
        },
        {
            "key": "mincit-innovacion",
            "name": "MinCIT Convocatorias",
            "base_url": "https://convocatoriasturismo.mincit.gov.co/listado-convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "innovacion", "emprendimiento"],
            "allowed_domains": ["mincit.gov.co", "www.mincit.gov.co", "convocatoriasturismo.mincit.gov.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "lundbeck-foundation",
            "name": "Lundbeck Foundation Grants",
            "base_url": "https://lundbeckfonden.com/en/grants-prizes/apply-grants",
            "country": "Denmark",
            "region": "Europe",
            "source_type": "html",
            "category": ["grants", "health", "neuroscience", "research"],
            "allowed_domains": ["lundbeckfonden.com"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "velux-foundation",
            "name": "Velux Fonden Current Calls",
            "base_url": "https://veluxfonden.dk/en/basic-page/current-calls",
            "country": "Denmark",
            "region": "Europe",
            "source_type": "html",
            "category": ["grants", "research", "sustainability"],
            "allowed_domains": ["veluxfonden.dk"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "isciii-convocatorias",
            "name": "ISCIII Convocatorias (BDN)",
            "base_url": "https://www.infosubvenciones.es/bdnstrans/api/convocatorias/busqueda?descripcion=Instituto+de+Salud+Carlos+III",
            "country": "Spain",
            "region": "Europe",
            "source_type": "api",
            "category": ["convocatorias", "health", "research"],
            "allowed_domains": ["infosubvenciones.es", "www.infosubvenciones.es", "isciii.es", "www.isciii.es"],
            "scraping_frequency": "daily",
        },
        {
            "key": "cdti-convocatorias",
            "name": "CDTI Convocatorias (BDN)",
            "base_url": "https://www.infosubvenciones.es/bdnstrans/api/convocatorias/busqueda?descripcion=CDTI",
            "country": "Spain",
            "region": "Europe",
            "source_type": "api",
            "category": ["convocatorias", "innovacion", "research"],
            "allowed_domains": ["infosubvenciones.es", "www.infosubvenciones.es", "cdti.es", "www.cdti.es"],
            "scraping_frequency": "daily",
        },
        {
            "key": "idrc-funding",
            "name": "IDRC Funding Opportunities",
            "base_url": "https://idrc-crdi.ca/en/funding",
            "country": "Canada",
            "region": "Global",
            "source_type": "html",
            "category": ["grants", "research", "development"],
            "allowed_domains": ["idrc-crdi.ca", "www.idrc-crdi.ca"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "usaid-grants",
            "name": "USAID Grants (Grants.gov)",
            "base_url": "https://api.grants.gov/v1/api/search2",
            "country": "United States",
            "region": "Global",
            "source_type": "api",
            "category": ["grants", "cooperation", "international development"],
            "allowed_domains": ["api.grants.gov", "www.grants.gov", "grants.gov"],
            "scraping_frequency": "daily",
        },
        {
            "key": "giz-funding",
            "name": "GIZ Partner Funding",
            "base_url": "https://www.giz.de/en/partner/funding",
            "country": "Germany",
            "region": "Global",
            "source_type": "html",
            "category": ["cooperation", "development", "funding"],
            "allowed_domains": ["giz.de", "www.giz.de", "ausschreibungen.giz.de"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "cordis-h2020",
            "name": "CORDIS Horizon 2020 Projects",
            "base_url": "https://cordis.europa.eu/api/search/results?q=contenttype%3D%27project%27%20AND%20frameworkProgramme%3D%27H2020%27&p=1&num=50&format=json&srt=%2FlastUpdateDate%3Adecreasing",
            "country": "European Union",
            "region": "Europe",
            "source_type": "api",
            "category": ["grants", "research", "innovation", "horizon 2020"],
            "allowed_domains": ["cordis.europa.eu"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "eic-accelerator",
            "name": "EIC Accelerator (SEDIA)",
            "base_url": "https://api.tech.ec.europa.eu/search-api/prod/rest/search",
            "country": "European Union",
            "region": "Europe",
            "source_type": "api",
            "category": ["grants", "innovation", "startup", "eic accelerator"],
            "allowed_domains": ["api.tech.ec.europa.eu", "ec.europa.eu"],
            "scraping_frequency": "daily",
        },
        {
            "key": "global-innovation-fund",
            "name": "Global Innovation Fund",
            "base_url": "https://www.globalinnovation.fund/apply-for-funding/",
            "country": "International",
            "region": "Global",
            "source_type": "html",
            "category": ["grants", "innovation", "development", "social impact"],
            "allowed_domains": ["globalinnovation.fund", "www.globalinnovation.fund"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "procolombia-convocatorias",
            "name": "ProColombia Convocatorias",
            "base_url": "https://www.procolombia.co/convocatorias-exportaciones",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "exportacion", "turismo", "internacionalizacion"],
            "allowed_domains": ["procolombia.co", "www.procolombia.co", "groovy-hickory-42b.notion.site", "drive.google.com"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "anii-uruguay",
            "name": "ANII Uruguay Convocatorias",
            "base_url": "https://anii.org.uy/apoyos/investigacion/",
            "country": "Uruguay",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "investigacion", "innovacion", "emprendimiento"],
            "allowed_domains": ["anii.org.uy", "www.anii.org.uy"],
            "scraping_frequency": "daily",
        },

        # ================================================================
        # COLOMBIA — 30 new sources
        # ================================================================
        {
            "key": "sena-convocatorias",
            "name": "SENA Convocatorias",
            "base_url": "https://www.sena.edu.co/es-co/trabajo/Paginas/convocatorias.aspx",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "formacion", "emprendimiento"],
            "allowed_domains": ["sena.edu.co", "www.sena.edu.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "rutann-convocatorias",
            "name": "Ruta N Medellín",
            "base_url": "https://www.rutanmedellin.org/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "innovacion", "emprendimiento"],
            "allowed_domains": ["rutanmedellin.org", "www.rutanmedellin.org"],
            "scraping_frequency": "daily",
        },
        {
            "key": "camara-comercio-bogota",
            "name": "Cámara de Comercio de Bogotá — Convocatorias",
            "base_url": "https://www.ccb.org.co/Transformar-Bogota/Convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "emprendimiento", "innovacion"],
            "allowed_domains": ["ccb.org.co", "www.ccb.org.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "connect-bogota",
            "name": "Connect Bogotá Región",
            "base_url": "https://connectbogota.org/convocatorias/",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "innovacion", "emprendimiento"],
            "allowed_domains": ["connectbogota.org", "www.connectbogota.org"],
            "scraping_frequency": "daily",
        },
        {
            "key": "bancoldex-convocatorias",
            "name": "Bancóldex Convocatorias",
            "base_url": "https://www.bancoldex.com/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "financiamiento", "emprendimiento"],
            "allowed_domains": ["bancoldex.com", "www.bancoldex.com"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "findeter-convocatorias",
            "name": "Findeter Convocatorias",
            "base_url": "https://www.findeter.gov.co/publicaciones/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "financiamiento", "infraestructura"],
            "allowed_domains": ["findeter.gov.co", "www.findeter.gov.co"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "fondo-nacional-garantias",
            "name": "Fondo Nacional de Garantías",
            "base_url": "https://www.fng.gov.co/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "financiamiento", "garantias"],
            "allowed_domains": ["fng.gov.co", "www.fng.gov.co"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "icfes-convocatorias",
            "name": "ICFES Convocatorias",
            "base_url": "https://www.icfes.gov.co/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "educacion", "investigacion"],
            "allowed_domains": ["icfes.gov.co", "www.icfes.gov.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "invima-convocatorias",
            "name": "INVIMA Convocatorias",
            "base_url": "https://www.invima.gov.co/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "salud", "regulacion"],
            "allowed_domains": ["invima.gov.co", "www.invima.gov.co"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "agrosavia-convocatorias",
            "name": "AGROSAVIA Convocatorias",
            "base_url": "https://www.agrosavia.co/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "agro", "investigacion"],
            "allowed_domains": ["agrosavia.co", "www.agrosavia.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "dane-convocatorias",
            "name": "DANE Convocatorias y Concursos",
            "base_url": "https://www.dane.gov.co/index.php/convocatorias-y-concursos",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "estadistica", "investigacion"],
            "allowed_domains": ["dane.gov.co", "www.dane.gov.co"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "ideam-convocatorias",
            "name": "IDEAM Convocatorias",
            "base_url": "https://www.ideam.gov.co/web/entidad/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "ambiental", "investigacion"],
            "allowed_domains": ["ideam.gov.co", "www.ideam.gov.co"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "universidad-nacional-colombia",
            "name": "Universidad Nacional de Colombia — Investigación",
            "base_url": "https://investigacion.unal.edu.co/convocatorias/",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "investigacion", "academia"],
            "allowed_domains": ["unal.edu.co", "investigacion.unal.edu.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "universidad-antioquia",
            "name": "Universidad de Antioquia — Investigación",
            "base_url": "https://www.udea.edu.co/wps/portal/udea/web/inicio/investigacion/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "investigacion", "academia"],
            "allowed_domains": ["udea.edu.co", "www.udea.edu.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "uniandes-investigacion",
            "name": "Universidad de los Andes — Investigación",
            "base_url": "https://investigaciones.uniandes.edu.co/convocatorias/",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "investigacion", "academia"],
            "allowed_domains": ["uniandes.edu.co", "investigaciones.uniandes.edu.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "sgc-colombia",
            "name": "Servicio Geológico Colombiano — Convocatorias",
            "base_url": "https://www.sgc.gov.co/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "geociencias", "investigacion"],
            "allowed_domains": ["sgc.gov.co", "www.sgc.gov.co"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "artesanias-colombia",
            "name": "Artesanías de Colombia — Convocatorias",
            "base_url": "https://artesaniasdecolombia.com.co/PortalAC/C_convocatorias/",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "cultura", "emprendimiento"],
            "allowed_domains": ["artesaniasdecolombia.com.co"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "innpulsa-colombia-startup",
            "name": "iNNpulsa Colombia — Startup y Emprendimiento",
            "base_url": "https://www.innpulsacolombia.com/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "startup", "emprendimiento"],
            "allowed_domains": ["innpulsacolombia.com", "www.innpulsacolombia.com"],
            "scraping_frequency": "daily",
        },
        {
            "key": "dian-contratacion",
            "name": "DIAN Contratación y Convocatorias",
            "base_url": "https://www.dian.gov.co/dian/entidad/Paginas/Contratacion.aspx",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "contratacion", "publico"],
            "allowed_domains": ["dian.gov.co", "www.dian.gov.co"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "colombia-productiva",
            "name": "Colombia Productiva — Convocatorias",
            "base_url": "https://www.colombiaproductiva.com/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "productividad", "industria"],
            "allowed_domains": ["colombiaproductiva.com", "www.colombiaproductiva.com"],
            "scraping_frequency": "daily",
        },
        {
            "key": "supersolidaria-convocatorias",
            "name": "SuperSolidaria — Convocatorias",
            "base_url": "https://www.supersolidaria.gov.co/es/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "solidaria", "social"],
            "allowed_domains": ["supersolidaria.gov.co", "www.supersolidaria.gov.co"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "colombia-cientifica",
            "name": "Colombia Científica — Convocatorias",
            "base_url": "https://www.colombiacientifica.gov.co/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "investigacion", "ciencia"],
            "allowed_domains": ["colombiacientifica.gov.co", "www.colombiacientifica.gov.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "fondo-emprender-sena",
            "name": "Fondo Emprender — SENA",
            "base_url": "https://www.fondoemprender.com/SitePages/Convocatorias.aspx",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "emprendimiento", "capital-semilla"],
            "allowed_domains": ["fondoemprender.com", "www.fondoemprender.com"],
            "scraping_frequency": "daily",
        },
        {
            "key": "camara-comercio-medellin",
            "name": "Cámara de Comercio de Medellín — Convocatorias",
            "base_url": "https://www.camaramedellin.com.co/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "emprendimiento", "innovacion"],
            "allowed_domains": ["camaramedellin.com.co", "www.camaramedellin.com.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "camara-comercio-cali",
            "name": "Cámara de Comercio de Cali — Convocatorias",
            "base_url": "https://www.ccc.org.co/convocatorias/",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "emprendimiento", "innovacion"],
            "allowed_domains": ["ccc.org.co", "www.ccc.org.co"],
            "scraping_frequency": "daily",
        },

        # ================================================================
        # LATINOAMÉRICA — 20 new sources
        # ================================================================
        {
            "key": "conacyt-mexico",
            "name": "CONAHCYT México — Convocatorias",
            "base_url": "https://conahcyt.mx/convocatorias/",
            "country": "Mexico",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "ciencia", "investigacion"],
            "allowed_domains": ["conahcyt.mx", "www.conahcyt.mx"],
            "scraping_frequency": "daily",
        },
        {
            "key": "fondecyt-chile",
            "name": "FONDECYT Chile",
            "base_url": "https://www.anid.cl/concursos/",
            "country": "Chile",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "ciencia", "investigacion"],
            "allowed_domains": ["anid.cl", "www.anid.cl"],
            "scraping_frequency": "daily",
        },
        {
            "key": "conicet-argentina",
            "name": "CONICET Argentina — Becas y Convocatorias",
            "base_url": "https://convocatorias.conicet.gov.ar/",
            "country": "Argentina",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "ciencia", "becas"],
            "allowed_domains": ["conicet.gov.ar", "convocatorias.conicet.gov.ar"],
            "scraping_frequency": "daily",
        },
        {
            "key": "fapesp-brasil",
            "name": "FAPESP Brasil — Oportunidades",
            "base_url": "https://fapesp.br/oportunidades/",
            "country": "Brazil",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "ciencia", "investigacion"],
            "allowed_domains": ["fapesp.br", "www.fapesp.br"],
            "scraping_frequency": "daily",
        },
        {
            "key": "cnpq-brasil",
            "name": "CNPq Brasil — Chamadas",
            "base_url": "https://www.gov.br/cnpq/pt-br/assuntos/noticias/cnpq-em-acao",
            "country": "Brazil",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "ciencia", "becas"],
            "allowed_domains": ["gov.br", "www.gov.br"],
            "scraping_frequency": "daily",
        },
        {
            "key": "senescyt-ecuador",
            "name": "SENESCYT Ecuador — Becas",
            "base_url": "https://www.educacionsuperior.gob.ec/becas/",
            "country": "Ecuador",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "becas", "educacion"],
            "allowed_domains": ["educacionsuperior.gob.ec", "www.educacionsuperior.gob.ec"],
            "scraping_frequency": "daily",
        },
        {
            "key": "concytec-peru",
            "name": "CONCYTEC Perú — Concursos",
            "base_url": "https://www.gob.pe/concytec",
            "country": "Peru",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "ciencia", "investigacion"],
            "allowed_domains": ["gob.pe", "www.gob.pe"],
            "scraping_frequency": "daily",
        },
        {
            "key": "fonacyt-bolivia",
            "name": "FONACYT Bolivia",
            "base_url": "https://www.facebook.com/FonacytBolivia",
            "country": "Bolivia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "ciencia", "investigacion"],
            "allowed_domains": ["facebook.com"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "conacyt-paraguay",
            "name": "CONACYT Paraguay — Convocatorias",
            "base_url": "https://www.conacyt.gov.py/convocatorias",
            "country": "Paraguay",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "ciencia", "investigacion"],
            "allowed_domains": ["conacyt.gov.py", "www.conacyt.gov.py"],
            "scraping_frequency": "daily",
        },
        {
            "key": "bid-convocatorias",
            "name": "BID — Convocatorias y Licitaciones",
            "base_url": "https://www.iadb.org/es/convocatorias",
            "country": "International",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "financiamiento", "desarrollo"],
            "allowed_domains": ["iadb.org", "www.iadb.org"],
            "scraping_frequency": "daily",
        },
        {
            "key": "caf-convocatorias",
            "name": "CAF — Convocatorias para el Desarrollo",
            "base_url": "https://www.caf.com/es/oportunidades/consultoria-y-contrataciones/",
            "country": "International",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "financiamiento", "infraestructura"],
            "allowed_domains": ["caf.com", "www.caf.com"],
            "scraping_frequency": "daily",
        },
        {
            "key": "oei-convocatorias",
            "name": "OEI — Convocatorias Iberoamericanas",
            "base_url": "https://oei.int/oficinas/secretaria-general/convocatorias",
            "country": "International",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "educacion", "cultura"],
            "allowed_domains": ["oei.int", "www.oei.int"],
            "scraping_frequency": "daily",
        },
        {
            "key": "cepal-convocatorias",
            "name": "CEPAL — Convocatorias",
            "base_url": "https://www.cepal.org/es/convocatorias",
            "country": "International",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "desarrollo", "investigacion"],
            "allowed_domains": ["cepal.org", "www.cepal.org"],
            "scraping_frequency": "daily",
        },
        {
            "key": "flacso-convocatorias",
            "name": "FLACSO — Convocatorias Académicas",
            "base_url": "https://www.flacso.org/convocatorias",
            "country": "International",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "academia", "investigacion"],
            "allowed_domains": ["flacso.org", "www.flacso.org"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "celac-convocatorias",
            "name": "CELAC — Convocatorias Regionales",
            "base_url": "https://celacinternational.org/convocatorias/",
            "country": "International",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "cooperacion", "desarrollo"],
            "allowed_domains": ["celacinternational.org"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "aladi-convocatorias",
            "name": "ALADI — Oportunidades Comerciales",
            "base_url": "https://www.aladi.org/sitioaladi/convocatorias/",
            "country": "International",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "comercio", "cooperacion"],
            "allowed_domains": ["aladi.org", "www.aladi.org"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "sgc-convocatorias",
            "name": "SGC — Convocatorias Geotérmicas LatAm",
            "base_url": "https://www.segib.org/convocatorias/",
            "country": "International",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "cooperacion", "desarrollo"],
            "allowed_domains": ["segib.org", "www.segib.org"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "parlatino-convocatorias",
            "name": "Parlatino — Convocatorias",
            "base_url": "https://parlatino.org/convocatorias/",
            "country": "International",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "politica", "cooperacion"],
            "allowed_domains": ["parlatino.org", "www.parlatino.org"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "argentina-investigacion",
            "name": "Argentina.gob.ar — Ciencia y Tecnología",
            "base_url": "https://www.argentina.gob.ar/ciencia/convocatorias",
            "country": "Argentina",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "ciencia", "investigacion"],
            "allowed_domains": ["argentina.gob.ar", "www.argentina.gob.ar"],
            "scraping_frequency": "daily",
        },
        {
            "key": "cfe-uruguay",
            "name": "CFE Uruguay — Convocatorias de Investigación",
            "base_url": "https://www.cfe.edu.uy/index.php/todas-convocatorias",
            "country": "Uruguay",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "educacion", "investigacion"],
            "allowed_domains": ["cfe.edu.uy", "www.cfe.edu.uy"],
            "scraping_frequency": "daily",
        },

        # ================================================================
        # MORE COLOMBIA — 15 adicionales
        # ================================================================
        {
            "key": "mintic-convocatorias",
            "name": "MinTIC Colombia — Convocatorias TIC",
            "base_url": "https://www.mintic.gov.co/portal/inicio/Convocatorias/",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "tic", "innovacion"],
            "allowed_domains": ["mintic.gov.co", "www.mintic.gov.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "minagricultura-convocatorias",
            "name": "MinAgricultura Colombia",
            "base_url": "https://www.minagricultura.gov.co/convocatorias/Paginas/default.aspx",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "agro", "rural"],
            "allowed_domains": ["minagricultura.gov.co", "www.minagricultura.gov.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "minsalud-convocatorias",
            "name": "MinSalud Colombia — Convocatorias",
            "base_url": "https://www.minsalud.gov.co/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "salud", "investigacion"],
            "allowed_domains": ["minsalud.gov.co", "www.minsalud.gov.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "minambiente-colombia",
            "name": "MinAmbiente Colombia — Convocatorias",
            "base_url": "https://www.minambiente.gov.co/convocatorias/",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "ambiental", "sostenibilidad"],
            "allowed_domains": ["minambiente.gov.co", "www.minambiente.gov.co"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "univalle-investigacion",
            "name": "Universidad del Valle — Convocatorias",
            "base_url": "https://www.univalle.edu.co/investigacion/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "investigacion", "academia"],
            "allowed_domains": ["univalle.edu.co", "www.univalle.edu.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "uis-investigacion",
            "name": "UIS — Convocatorias de Investigación",
            "base_url": "https://www.uis.edu.co/webUIS/es/investigacionExtension/convocatorias.html",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "investigacion", "academia"],
            "allowed_domains": ["uis.edu.co", "www.uis.edu.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "javeriana-investigacion",
            "name": "Pontificia Universidad Javeriana — Convocatorias",
            "base_url": "https://www.javeriana.edu.co/investigacion/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "investigacion", "academia"],
            "allowed_domains": ["javeriana.edu.co", "www.javeriana.edu.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "eafit-investigacion",
            "name": "Universidad EAFIT — Convocatorias",
            "base_url": "https://www.eafit.edu.co/investigacion/convocatorias/Paginas/inicio.aspx",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "investigacion", "academia"],
            "allowed_domains": ["eafit.edu.co", "www.eafit.edu.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "uptc-investigacion",
            "name": "UPTC — Convocatorias de Investigación",
            "base_url": "https://www.uptc.edu.co/investigacion/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "investigacion", "academia"],
            "allowed_domains": ["uptc.edu.co", "www.uptc.edu.co"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "colciencias-historico",
            "name": "Colciencias — Archivo de Convocatorias",
            "base_url": "https://minciencias.gov.co/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "ciencia", "becas"],
            "allowed_domains": ["minciencias.gov.co", "www.minciencias.gov.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "icbf-convocatorias",
            "name": "ICBF — Convocatorias y Contratación",
            "base_url": "https://www.icbf.gov.co/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "social", "infancia"],
            "allowed_domains": ["icbf.gov.co", "www.icbf.gov.co"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "procolombia-inversion",
            "name": "ProColombia — Oportunidades de Inversión",
            "base_url": "https://investincolombia.com.co/es/convocatorias",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "inversion", "negocios"],
            "allowed_domains": ["investincolombia.com.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "camara-comercio-bquilla",
            "name": "Cámara de Comercio de Barranquilla",
            "base_url": "https://www.camarabaq.org.co/convocatorias/",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "emprendimiento", "innovacion"],
            "allowed_domains": ["camarabaq.org.co", "www.camarabaq.org.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "sennova-sena",
            "name": "SENNOVA SENA — Innovación y Desarrollo Tecnológico",
            "base_url": "https://www.sena.edu.co/es-co/trabajo/Paginas/sennova.aspx",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "innovacion", "tecnologia"],
            "allowed_domains": ["sena.edu.co", "www.sena.edu.co"],
            "scraping_frequency": "daily",
        },
        {
            "key": "acac-colombia",
            "name": "ACAC — Convocatorias Científicas",
            "base_url": "https://www.acac.org.co/convocatorias/",
            "country": "Colombia",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "ciencia", "investigacion"],
            "allowed_domains": ["acac.org.co", "www.acac.org.co"],
            "scraping_frequency": "weekly",
        },

        # ================================================================
        # BRAZIL — 10 new sources (biggest LatAm funding ecosystem)
        # ================================================================
        {
            "key": "finep-brasil",
            "name": "FINEP Brasil — Innovación y Tecnología",
            "base_url": "https://www.finep.gov.br/chamadas-publicas",
            "country": "Brazil",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "innovacion", "financiamiento"],
            "allowed_domains": ["finep.gov.br", "www.finep.gov.br"],
            "scraping_frequency": "daily",
        },
        {
            "key": "capes-brasil",
            "name": "CAPES Brasil — Becas y Cooperación",
            "base_url": "https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/bolsas",
            "country": "Brazil",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "becas", "educacion"],
            "allowed_domains": ["gov.br", "www.gov.br"],
            "scraping_frequency": "daily",
        },
        {
            "key": "embrapii-brasil",
            "name": "EMBRAPII Brasil — Innovación Industrial",
            "base_url": "https://embrapii.org.br/editais/",
            "country": "Brazil",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "innovacion", "industria"],
            "allowed_domains": ["embrapii.org.br", "www.embrapii.org.br"],
            "scraping_frequency": "daily",
        },
        {
            "key": "fapesp-pipe",
            "name": "FAPESP PIPE — Innovación en Pequeñas Empresas",
            "base_url": "https://fapesp.br/pipe/",
            "country": "Brazil",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "startup", "innovacion"],
            "allowed_domains": ["fapesp.br", "www.fapesp.br"],
            "scraping_frequency": "daily",
        },
        {
            "key": "faperj-brasil",
            "name": "FAPERJ Río de Janeiro",
            "base_url": "https://www.faperj.br/?id=3689.2.7",
            "country": "Brazil",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "ciencia", "estadual"],
            "allowed_domains": ["faperj.br", "www.faperj.br"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "fapemig-brasil",
            "name": "FAPEMIG Minas Gerais",
            "base_url": "https://fapemig.br/pt/menu/editais/",
            "country": "Brazil",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "ciencia", "estadual"],
            "allowed_domains": ["fapemig.br", "www.fapemig.br"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "sebrae-brasil",
            "name": "SEBRAE Brasil — Emprendimiento",
            "base_url": "https://www.sebrae.com.br/sites/PortalSebrae/editais",
            "country": "Brazil",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "emprendimiento", "pyme"],
            "allowed_domains": ["sebrae.com.br", "www.sebrae.com.br"],
            "scraping_frequency": "daily",
        },
        {
            "key": "bndes-brasil",
            "name": "BNDES Brasil — Financiamiento",
            "base_url": "https://www.bndes.gov.br/wps/portal/site/home/apoio/chamadas-publicas",
            "country": "Brazil",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "financiamiento", "desarrollo"],
            "allowed_domains": ["bndes.gov.br", "www.bndes.gov.br"],
            "scraping_frequency": "daily",
        },
        {
            "key": "inct-brasil",
            "name": "INCT Brasil — Institutos de Ciencia y Tecnología",
            "base_url": "https://www.gov.br/cnpq/pt-br/assuntos/institutos-nacionais-de-ciencia-e-tecnologia",
            "country": "Brazil",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "ciencia", "investigacion"],
            "allowed_domains": ["gov.br"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "anp-brasil",
            "name": "ANP Brasil — Investigación en Energía",
            "base_url": "https://www.gov.br/anp/pt-br/assuntos/pesquisa-desenvolvimento-e-inovacao",
            "country": "Brazil",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "energia", "investigacion"],
            "allowed_domains": ["gov.br", "anp.gov.br"],
            "scraping_frequency": "weekly",
        },

        # ================================================================
        # MORE INTERNATIONAL — 15 new sources
        # ================================================================
        {
            "key": "world-bank-procurement",
            "name": "World Bank — Procurement and Grants",
            "base_url": "https://projects.worldbank.org/en/projects-operations/procurement",
            "country": "International",
            "region": "Global",
            "source_type": "html",
            "category": ["convocatorias", "financiamiento", "desarrollo"],
            "allowed_domains": ["worldbank.org", "projects.worldbank.org"],
            "scraping_frequency": "daily",
        },
        {
            "key": "undp-funding",
            "name": "UNDP — Funding Opportunities",
            "base_url": "https://www.undp.org/procurement",
            "country": "International",
            "region": "Global",
            "source_type": "html",
            "category": ["convocatorias", "financiamiento", "desarrollo"],
            "allowed_domains": ["undp.org", "www.undp.org"],
            "scraping_frequency": "daily",
        },
        {
            "key": "ford-foundation-grants",
            "name": "Ford Foundation — Grants",
            "base_url": "https://www.fordfoundation.org/work/our-grants/",
            "country": "International",
            "region": "Global",
            "source_type": "html",
            "category": ["convocatorias", "filantropia", "social"],
            "allowed_domains": ["fordfoundation.org", "www.fordfoundation.org"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "rockefeller-foundation",
            "name": "Rockefeller Foundation — Grants",
            "base_url": "https://www.rockefellerfoundation.org/grants/",
            "country": "International",
            "region": "Global",
            "source_type": "html",
            "category": ["convocatorias", "filantropia", "innovacion"],
            "allowed_domains": ["rockefellerfoundation.org", "www.rockefellerfoundation.org"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "mozilla-foundation",
            "name": "Mozilla Foundation — Grants",
            "base_url": "https://foundation.mozilla.org/en/what-we-fund/awards/",
            "country": "International",
            "region": "Global",
            "source_type": "html",
            "category": ["convocatorias", "internet", "innovacion"],
            "allowed_domains": ["foundation.mozilla.org"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "interamerican-foundation",
            "name": "IAF — Inter-American Foundation Grants",
            "base_url": "https://www.iaf.gov/apply-for-grant/",
            "country": "United States",
            "region": "LatAm",
            "source_type": "html",
            "category": ["convocatorias", "desarrollo", "comunitario"],
            "allowed_domains": ["iaf.gov", "www.iaf.gov"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "global-environment-facility",
            "name": "GEF — Global Environment Facility",
            "base_url": "https://www.thegef.org/projects-operations/calls-for-proposals",
            "country": "International",
            "region": "Global",
            "source_type": "html",
            "category": ["convocatorias", "ambiental", "sostenibilidad"],
            "allowed_domains": ["thegef.org", "www.thegef.org"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "green-climate-fund",
            "name": "GCF — Green Climate Fund",
            "base_url": "https://www.greenclimate.fund/projects/call-for-proposals",
            "country": "International",
            "region": "Global",
            "source_type": "html",
            "category": ["convocatorias", "clima", "sostenibilidad"],
            "allowed_domains": ["greenclimate.fund", "www.greenclimate.fund"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "jica-japan",
            "name": "JICA Japan — Partnership Program",
            "base_url": "https://www.jica.go.jp/english/our_work/types_of_assistance/oda_loan/oda_loans.html",
            "country": "Japan",
            "region": "Asia",
            "source_type": "html",
            "category": ["convocatorias", "cooperacion", "desarrollo"],
            "allowed_domains": ["jica.go.jp", "www.jica.go.jp"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "koica-korea",
            "name": "KOICA Korea — Convocatorias",
            "base_url": "https://www.koica.go.kr/sites/koica_en/index.do",
            "country": "South Korea",
            "region": "Asia",
            "source_type": "html",
            "category": ["convocatorias", "cooperacion", "desarrollo"],
            "allowed_domains": ["koica.go.kr", "www.koica.go.kr"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "aecid-espana",
            "name": "AECID España — Cooperación Española",
            "base_url": "https://www.aecid.es/convocatorias",
            "country": "Spain",
            "region": "Europe",
            "source_type": "html",
            "category": ["convocatorias", "cooperacion", "desarrollo"],
            "allowed_domains": ["aecid.es", "www.aecid.es"],
            "scraping_frequency": "daily",
        },
        {
            "key": "giz-alemania",
            "name": "GIZ Alemania — Licitaciones",
            "base_url": "https://www.giz.de/en/html/ausschreibungen.html",
            "country": "Germany",
            "region": "Europe",
            "source_type": "html",
            "category": ["convocatorias", "cooperacion", "desarrollo"],
            "allowed_domains": ["giz.de", "www.giz.de"],
            "scraping_frequency": "daily",
        },
        {
            "key": "sida-sweden",
            "name": "SIDA Suecia — Research Cooperation",
            "base_url": "https://www.sida.se/en/for-partners/calls-and-announcements",
            "country": "Sweden",
            "region": "Europe",
            "source_type": "html",
            "category": ["convocatorias", "cooperacion", "investigacion"],
            "allowed_domains": ["sida.se", "www.sida.se"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "norad-norway",
            "name": "NORAD Noruega — Grants",
            "base_url": "https://www.norad.no/en/front/grants/",
            "country": "Norway",
            "region": "Europe",
            "source_type": "html",
            "category": ["convocatorias", "cooperacion", "desarrollo"],
            "allowed_domains": ["norad.no", "www.norad.no"],
            "scraping_frequency": "weekly",
        },
        {
            "key": "danida-denmark",
            "name": "DANIDA Dinamarca — Research Grants",
            "base_url": "https://um.dk/en/danida/research/calls-for-proposals",
            "country": "Denmark",
            "region": "Europe",
            "source_type": "html",
            "category": ["convocatorias", "cooperacion", "investigacion"],
            "allowed_domains": ["um.dk", "www.um.dk"],
            "scraping_frequency": "weekly",
        },
    ]

    inserted = 0
    updated = 0
    for definition in source_definitions:
        source = db.scalar(select(Source).where(Source.key == definition["key"]))
        if source:
            source.organization_id = organization.id
            source.name = definition["name"]
            source.base_url = definition["base_url"]
            source.country = definition["country"]
            source.region = definition["region"]
            source.source_type = definition["source_type"]
            source.category = definition["category"]
            source.scraping_frequency = definition.get("scraping_frequency", "daily")
            source.allowed_domains = definition["allowed_domains"]
            source.enabled = True
            updated += 1
            continue
        db.add(
            Source(
                organization_id=organization.id,
                name=definition["name"],
                key=definition["key"],
                base_url=definition["base_url"],
                country=definition["country"],
                region=definition["region"],
                source_type=definition["source_type"],
                category=definition["category"],
                scraping_frequency=definition.get("scraping_frequency", "daily"),
                allowed_domains=definition["allowed_domains"],
            )
        )
        inserted += 1
    return {"inserted": inserted, "updated": updated, "total": len(source_definitions)}


def seed() -> None:
    create_all()
    db = SessionLocal()
    try:
        organization = db.scalar(select(Organization).where(Organization.slug == "convocaradar-local"))
        if not organization:
            organization = Organization(
                name="ConvocaRadar Local",
                slug="convocaradar-local",
                type="university",
                country="Colombia",
                website="https://convocaradar.local",
            )
            db.add(organization)
            db.flush()
            db.add(
                OrganizationProfile(
                    organization_id=organization.id,
                    description="Perfil local para vigilancia de innovacion, investigacion y emprendimiento.",
                    country="Colombia",
                    regions_of_interest=["LatAm", "Global"],
                    organization_type="university",
                    areas_of_interest=["innovacion", "investigacion", "inteligencia artificial", "sostenibilidad"],
                    funding_types=["grant", "cofinancing", "award"],
                    min_funding_amount=10000000,
                    max_funding_amount=500000000,
                    preferred_currencies=["COP", "USD", "EUR"],
                    eligible_international=True,
                    languages=["es", "en"],
                    has_research_groups=True,
                    has_company_partners=True,
                    has_university_partners=True,
                    application_capacity="high",
                )
            )

        seed_default_sources(db, organization)

        db.commit()
    finally:
        db.close()


if __name__ == "__main__":
    seed()

